### ISSUE TITLE
Add option for license: UNLICENSED

### ISSUE THREAD

**Issue by Flet** [ungoldman/module-init#34]
Any thoughts on adding UNLICENSED as an option for licenses? Possibly also set "private": "true" in `package.json`?

**Comment by ngoldman** [comment]
Sounds reasonable to me :+1:

**Comment by ungoldman** [comment]
Opting for allowing "private": "true" to be set and adding [The Unlicense](https://spdx.org/licenses/Unlicense) as a licensing option.

**Comment by Flet** [comment]
The Unlicense sounds like the opposite of UNLICENSED
https://docs.npmjs.com/files/package.json#license

>Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
>```js
{ "license": "UNLICENSED"}
```

**Comment by Flet** [comment]
also a very long issue on npm where this is discussed (was interesting to read)
https://github.com/npm/npm/issues/8918

...ultimately ending in this comment
>Both SEE LICENSE IN and UNLICENSED are defined and functional in the latest released versions of npm@2 and npm@3,

**Comment by ungoldman** [comment]
Oh I see! Thanks for clarifying, I should have looked it up :)

I will add that too.
