### ISSUE TITLE
EditorConfig ?

### ISSUE THREAD

**Issue by jokeyrhyme** [ungoldman/module-init#37]
Do you think it's worth setting up EditorConfig?
- http://editorconfig.org/

I'm building up a catch-all EditorConfig file here, which might be a useful starting point:
- https://github.com/jokeyrhyme/standard-editorconfig

**Comment by ungoldman** [comment]
Hi @jokeyrhyme! Thanks for opening an issue.

`module-init` already uses [`standard`](http://standardjs.com/) which takes care of avoiding a great deal of style issues. I feel like though an `.editorconfig` is an interesting concept, it may be open up a lot of possible [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding) in the future.

For now I'd like to leave editor configuration to each individual user and let `standard` do the work of ensuring consistent style for published modules.
